version: '3'
services:   
  db:
    # image to fetch from docker hub
    image: percona:8
    ports:
       - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=testuser"
      - "MYSQL_PASSWORD=admin123"
      - "MYSQL_DATABASE=backend"
  app_server1:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - app_server1:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: backend 
    links:
       - db:database
  app_server2:
    image: wordpress:latest
    volumes:
      - app_server2:/var/www/html
    ports: 
       - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: backend
    depends_on:
       - db
    links:
       - db:database
  nginx:
    image: nginx:latest
    ports:
     - 80:80
    depends_on:
       - mysql
       - app_server1
       - app_server2 
   
